### ISSUE TITLE
To many coma !

### ISSUE THREAD

**Issue by ghost** [zedafty/capitaine-vaudou#1]
https://github.com/zedafty/capitaine-vaudou/blob/15db3dc764da3d4558e3e7f13739fe426d14c5e9/doc/Properties.txt#L63

"speed_maneuver_modifier": 0, , "toggle_speed_maneuver_modifier": 0

**Comment by zedafty** [comment]
Thank you Jambon II, nice spot, no more too many commas by now ;)
